INSERT INTO users (email, username, password)
VALUES ('tigaj@gmail.com', 'Ammcef1', '1234'),
    ('pecujka@gmail.com', 'Amaca', '4343'),
    ('amejaa@gmail.com', 'Amaca', '4343'),
    ('najmladje@gmail.com', 'Amaca', '4343'),
    ('najsladje@gmail.com', 'Amaca', '4343'),
    ('najmanje@gmail.com', 'Amaca', '4343'),
    ('sejoselmalove@gmail.com', 'Amaca', '4343'),
    ('selmaisejo@gmail.com', 'Amaca', '4343'),
    ('snahoselma@gmail.com', 'Amaca', '4343'),
    ('selmakadric@gmail.com', 'Amaca', '4343'),
    ('shk@gmail.com', 'Amaca', '4343'),
    ('sabinabacevac@gmail.com', 'Amaca', '4343'),
    ('najstarije@gmail.com', 'Amaca', '4343'),
    ('plavo@gmail.com', 'Amaca', '4343'),
    ('zuto@gmail.com', 'Amaca', '4343'),
    ('narandzasto@gmail.com', 'Amaca', '4343'),
    ('zekonja@gmail.com', 'Amaca', '4343'),
    ('patkica@gmail.com', 'Amaca', '4343')
RETURNING *;