INSERT INTO users (email, username, password)
VALUES ('tigar@gmail.com', 'Ammcef1', '1234'),
    ('lav@gmail.com', 'Amaca', '4343'),
    ('zirafa@gmail.com', 'Amaca', '4343'),
    ('zbun@gmail.com', 'Amaca', '4343'),
    ('persun@gmail.com', 'Amaca', '4343'),
    ('makaze@gmail.com', 'Amaca', '4343'),
    ('vrata@gmail.com', 'Amaca', '4343'),
    ('drvo@gmail.com', 'Amaca', '4343'),
    ('strela@gmail.com', 'Amaca', '4343'),
    ('ormar@gmail.com', 'Amaca', '4343'),
    ('kisa@gmail.com', 'Amaca', '4343'),
    ('sunce@gmail.com', 'Amaca', '4343'),
    ('sneg@gmail.com', 'Amaca', '4343'),
    ('vazduh@gmail.com', 'Amaca', '4343'),
    ('voda@gmail.com', 'Amaca', '4343'),
    ('vetar@gmail.com', 'Amaca', '4343'),
    ('dom@gmail.com', 'Amaca', '4343'),
    ('onaj@gmail.com', 'Amaca', '4343')
RETURNING *;